2016-05-05 13:02:51,811:ERROR:STDERR:Traceback (most recent call last):
2016-05-05 13:02:51,812:ERROR:STDERR:  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.2\helpers\pydev\pydevd.py", line 2411, in <module>
2016-05-05 13:02:51,822:ERROR:STDERR:globals = debugger.run(setup['file'], None, None, is_module)
2016-05-05 13:02:51,825:ERROR:STDERR:  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.2\helpers\pydev\pydevd.py", line 1802, in run
2016-05-05 13:02:51,832:ERROR:STDERR:launch(file, globals, locals)  # execute the script
2016-05-05 13:02:51,832:ERROR:STDERR:  File "C:/Users/User/Documents/Year 3/Semester 2/Evolutionary Algorithms/Exercise/Ex1/main.py", line 110, in <module>
2016-05-05 13:02:51,835:ERROR:STDERR:git_handling(newpath)
2016-05-05 13:02:51,836:ERROR:STDERR:  File "C:/Users/User/Documents/Year 3/Semester 2/Evolutionary Algorithms/Exercise/Ex1/main.py", line 32, in git_handling
2016-05-05 13:02:51,838:ERROR:STDERR:index.add([new_file_path])  # add a new file to the index
2016-05-05 13:02:51,841:ERROR:STDERR:  File "C:\Anaconda2\lib\site-packages\git\index\base.py", line 745, in add
2016-05-05 13:02:51,845:ERROR:STDERR:entries_added.extend(self._entries_for_paths(paths, path_rewriter, fprogress, entries))
2016-05-05 13:02:51,845:ERROR:STDERR:  File "C:\Anaconda2\lib\site-packages\git\util.py", line 55, in wrapper
2016-05-05 13:02:51,846:ERROR:STDERR:return func(self, *args, **kwargs)
2016-05-05 13:02:51,848:ERROR:STDERR:  File "C:\Anaconda2\lib\site-packages\git\index\util.py", line 84, in set_git_working_dir
2016-05-05 13:02:51,849:ERROR:STDERR:return func(self, *args, **kwargs)
2016-05-05 13:02:51,851:ERROR:STDERR:  File "C:\Anaconda2\lib\site-packages\git\index\base.py", line 631, in _entries_for_paths
2016-05-05 13:02:51,854:ERROR:STDERR:entries_added.append(self._store_path(filepath, fprogress))
2016-05-05 13:02:51,855:ERROR:STDERR:  File "C:\Anaconda2\lib\site-packages\git\index\base.py", line 599, in _store_path
2016-05-05 13:02:51,858:ERROR:STDERR:istream = self.repo.odb.store(IStream(Blob.type, st.st_size, stream))
2016-05-05 13:02:51,859:ERROR:STDERR:  File "C:\Anaconda2\lib\site-packages\gitdb\db\loose.py", line 230, in store
2016-05-05 13:02:51,861:ERROR:STDERR:remove(obj_path)
2016-05-05 13:02:51,862:ERROR:STDERR:WindowsError
2016-05-05 13:02:51,864:ERROR:STDERR::
2016-05-05 13:02:51,865:ERROR:STDERR:[Error 5] Access is denied: u'C:\\Users\\User\\Documents\\Year 3\\Semester 2\\Evolutionary Algorithms\\Exercise\\Ex1\\.git\\objects\\e6\\9de29bb2d1d6434b8b29ae775ad8c2e48c5391'
2016-05-05 13:02:51,904:INFO:STDOUT:Backend Qt4Agg is interactive backend. Turning interactive mode on.
