2016-05-05 10:55:30,375:INFO:STDOUT:Test to standard out
2016-05-05 10:55:30,963:ERROR:STDERR:Traceback (most recent call last):
2016-05-05 10:55:30,964:ERROR:STDERR:  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.2\helpers\pydev\pydevd.py", line 2411, in <module>
2016-05-05 10:55:30,976:ERROR:STDERR:globals = debugger.run(setup['file'], None, None, is_module)
2016-05-05 10:55:30,977:ERROR:STDERR:  File "C:\Program Files (x86)\JetBrains\PyCharm Community Edition 5.0.2\helpers\pydev\pydevd.py", line 1802, in run
2016-05-05 10:55:30,986:ERROR:STDERR:launch(file, globals, locals)  # execute the script
2016-05-05 10:55:30,987:ERROR:STDERR:  File "C:/Users/User/Documents/Year 3/Semester 2/Evolutionary Algorithms/Exercise/Ex1/main.py", line 70, in <module>
2016-05-05 10:55:30,990:ERROR:STDERR:raise Exception('Test to standard error')
2016-05-05 10:55:30,992:ERROR:STDERR:Exception
2016-05-05 10:55:30,993:ERROR:STDERR::
2016-05-05 10:55:30,993:ERROR:STDERR:Test to standard error
